# Generated by Django 4.2.5 on 2023-09-20 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Response',
        ),
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default='This is a test'),
            preserve_default=False,
        ),
    ]
