# Generated by Django 4.2.5 on 2023-10-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_category_options_thread_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='category',
        ),
    ]
