# Generated by Django 4.2.5 on 2023-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_pub_date_blogpost_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
