# Generated by Django 4.2.5 on 2023-10-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSavingsInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_energy_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solar_system_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solar_system_lifetime', models.PositiveIntegerField()),
            ],
        ),
    ]
