# Generated by Django 4.2.5 on 2023-09-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpower', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
