# Generated by Django 4.2.5 on 2023-09-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpower', '0002_delete_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
